replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/user-service
  tag: "development-7a8905f"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
  grpcPort: 9090
istio:
  enabled: true
  host: "user-service"
  mtls:
    mode: STRICT
  authorization:
    internalCallers:
      - "cluster.local/ns/fitnest-dev/sa/identity-service"
      - "cluster.local/ns/fitnest-dev/sa/payment-service"
      - "cluster.local/ns/fitnest-dev/sa/api-gateway"
      - "cluster.local/ns/fitnest-dev/sa/storage-service"
      - "cluster.local/ns/fitnest-dev/sa/catalog-service"
hpa:
  enabled: false
  minReplicas: "1"
  maxReplicas: "3"
  cpuUtilization: "90"
  memoryUtilization: "450Mi"
jwt:
  secret: "your-jwt-secret-change-in-production"
env:
  SPRING_PROFILES_ACTIVE: dev
  SPRINGDOC_SERVER_URL: "https://dev-api.fitnest.az"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-shared:5432/fitnest_user?sslmode=disable"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "shared_password_root_123"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  LOGGING_LEVEL_ROOT: INFO
  LOGGING_LEVEL_AZ_FITNEST_USER: DEBUG
  LOGGING_LEVEL_AZ_FITNEST_ORDER: DEBUG
  LOGGING_LEVEL_AZ_FITNEST: DEBUG
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
  LOGGING_LEVEL_FEIGN_LOGGER: OFF
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: ""
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  JWT_SECRET: "your-jwt-secret-change-in-production"
  JWT_ISSUER: "fitnest"
  IDENTITY_SERVICE_URL: "http://identity-service:8080"
  ORDER_SERVICE_GRPC_ADDRESS: "dns:///order-service.fitnest-dev.svc.cluster.local:9090"
  NOTIFICATIONS_SERVICE_URL: "http://notifications-service:8080"
  NOTIFICATIONS_SERVICE_GRPC_HOST: "notifications-service"
  NOTIFICATIONS_SERVICE_GRPC_PORT: "9090"
  # gRPC TLS / mTLS options for internal service-to-service calls (used by gRPC clients)
  GRPC_USE_TLS: "false"
  GRPC_TLS_CLIENT_CERT: "/etc/certs/tls.crt"
  GRPC_TLS_CLIENT_KEY: "/etc/certs/tls.key"
  GRPC_TLS_CA_CERT: "/etc/certs/ca.crt"
  GRPC_SERVER_TLS_ENABLED: "false"
  JAVA_TOOL_OPTIONS: >
    -Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:MaxMetaspaceSize=256m -XX:+AlwaysPreTouch -Xss512k -XX:+ExitOnOutOfMemoryError

resources:
  requests:
    cpu: 59m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
