apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "app.fullname" . }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort | default 8080 }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpcPort | default 9090 }}
              protocol: TCP
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "vault://"
            - name: SPRING_CLOUD_VAULT_ENABLED
              value: "true"
            - name: SPRING_CLOUD_VAULT_URI
              value: "http://10.0.0.4:8200"
            - name: SPRING_CLOUD_VAULT_AUTHENTICATION
              value: "APPROLE"
            - name: SPRING_CLOUD_VAULT_APP_ROLE_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle-secret
                  key: role-id
            - name: SPRING_CLOUD_VAULT_APP_ROLE_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle-secret
                  key: secret-id
            - name: SPRING_CLOUD_VAULT_KV_BACKEND
              value: "secrets"
            - name: SPRING_CLOUD_VAULT_KV_DEFAULT_CONTEXT
              value: "{{ .Chart.Name }}/{{ .Values.vaultEnv | default "development" }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
